FROM ruby:2.4.1-alpine

RUN apk add --no-cache build-base

WORKDIR /app

COPY Gemfile* ./
RUN bundle --without "development test"

COPY . .

CMD ["/usr/local/bin/bundle","exec", "rackup", "-s", "Puma", "-o", "0.0.0.0", "-p", "8080"]
